### ISSUE TITLE
Testing Adding 444 API

### ISSUE THREAD

**Issue by kinlane** [api-search/inbox#118]
```
aid: test-add-4
name: Testing Adding 444 API
type: Contract
description: >-
  This is a contract APIs.json, providing a boilerplate contract that an API
  consumer, or potential API consumer can use to express what is expected when
  one company provides an API to another company.
image: https://kinlane-productions.s3.amazonaws.com/apis-json/apis-json-logo.jpg
tags:
  - Application Programming Interface
  - API
  - Contract
created: '2024-11-14'
modified: '2024-11-14'
url: http://example.com/apis.json
specificationVersion: '0.18'
apis:
  - aid: api-json-contract:api
    name: API Contract
    description: >-
      These are properties that are expected for any API being made available,
      defining the baseline contract between API producer and consumer.
    image: https://kinlane-productions.s3.amazonaws.com/apis-json/apis-json-logo.jpg
    humanURL: http://example.com
    baseURL: http://api.example.com
    tags:
      - API
      - Application Programming Interface
      - Contract
    properties:
      - type: Documentation
        url: http://example.com
      - type: OpenAPI
        url: properties/openapi.yml
    contact:
      - FN: Support
        email: support@example.com
common:
  - type: Authentication
    url: http://example.com/authentication
  - type: GettingStarted
    url: http://example.com/getting-started
  - type: Support
    url: http://example.com/support
  - type: Pricing
    url: http://example.com/pricing
  - type: StatusPage
    url: http://example.com/status-page
  - type: ChangeLog
    url: http://example.com/change-log
maintainers:
  - FN: API Commons
    email: info@apievangelist.com
```
